cmake_minimum_required(VERSION 3.12)
project(cpp17_learn)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
message(STATUS "Project Source Dir: ${PROJECT_SOURCE_DIR}")
message(STATUS "CMake Source Dir: ${CMAKE_SOURCE_DIR}")
add_executable(cpp17_fstream ${CMAKE_SOURCE_DIR}/src/cpp17/cpp17_fstream.cpp)
add_executable(cpp17_ini ${CMAKE_SOURCE_DIR}/src/cpp17/cpp17_ini.cpp)
add_executable(cpp17_variant ${CMAKE_SOURCE_DIR}/src/cpp17/cpp17_variant.cpp)
add_executable(cpp17_any ${CMAKE_SOURCE_DIR}/src/cpp17/cpp17_any.cpp)
add_executable(cpp17_optional ${CMAKE_SOURCE_DIR}/src/cpp17/cpp17_optional.cpp)
add_executable(cpp17_filesystem ${CMAKE_SOURCE_DIR}/src/cpp17/cpp17_filesystem.cpp)
add_executable(cpp17_tuple ${CMAKE_SOURCE_DIR}/src/cpp17/cpp17_tuple.cpp)
add_executable(cpp17_arg ${CMAKE_SOURCE_DIR}/src/cpp17/cpp17_arg.cpp)
add_executable(cpp17_fstream ${CMAKE_SOURCE_DIR}/src/cpp17/cpp17_fstream.cpp)
add_executable(cpp17_ini ${CMAKE_SOURCE_DIR}/src/cpp17/cpp17_ini.cpp)
add_executable(cpp17_variant ${CMAKE_SOURCE_DIR}/src/cpp17/cpp17_variant.cpp)
add_executable(cpp17_any ${CMAKE_SOURCE_DIR}/src/cpp17/cpp17_any.cpp)

add_executable(myset_b_tree ${CMAKE_SOURCE_DIR}/src/myset_b_tree.cpp)
add_executable(virtual_main ${CMAKE_SOURCE_DIR}/src/virtual_main.cpp)
add_executable(simple_alloc_main ${CMAKE_SOURCE_DIR}/src/simple_alloc_main.cpp)
add_executable(singleton ${CMAKE_SOURCE_DIR}/src/singleton.cpp)
add_executable(my ${CMAKE_SOURCE_DIR}/src/my.cpp)
add_executable(constexpr_if ${CMAKE_SOURCE_DIR}/src/constexpr_if.cpp)
