cmake_minimum_required(VERSION 3.28)
project(cpp23_learn)

set(CMAKE_CXX_STANDARD 23)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
message(STATUS "Project Source Dir: ${PROJECT_SOURCE_DIR}")
message(STATUS "CMake Source Dir: ${CMAKE_SOURCE_DIR}")

if(CMAKE_SYSTEM_NAME STREQUAL "Linux" AND NOT APPLE)
    add_executable(cpp23_barrier_main ${CMAKE_SOURCE_DIR}/src/cpp23/cpp23_barrier_main.cpp)
    add_executable(cpp23_stdfloat_example ${CMAKE_SOURCE_DIR}/src/cpp23/cpp23_stdfloat_example.cpp)
    add_executable(cpp23_expected_example ${CMAKE_SOURCE_DIR}/src/cpp23/cpp23_expected_example.cpp)
    add_executable(cpp23_chunk ${CMAKE_SOURCE_DIR}/src/cpp23/cpp23_chunk.cpp)
    add_executable(cpp23_split ${CMAKE_SOURCE_DIR}/src/cpp23/cpp23_split.cpp)
    add_executable(cpp23_spanstream_example ${CMAKE_SOURCE_DIR}/src/cpp23/cpp23_spanstream_example.cpp)
else()
    message(STATUS "Skipping C++23 features on macOS (not fully supported)")
endif()
