cmake_minimum_required(VERSION 3.28)
project(cpp23_learn)

set(CMAKE_CXX_STANDARD 23)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

message(STATUS "Project Source Dir: ${PROJECT_SOURCE_DIR}")
message(STATUS "CMake Source Dir: ${CMAKE_SOURCE_DIR}")

add_executable(cpp23_barrier_main ${CMAKE_SOURCE_DIR}/src/cpp23/cpp23_barrier_main.cpp)
add_executable(cpp23_stdfloat_example ${CMAKE_SOURCE_DIR}/src/cpp23/cpp23_stdfloat_example.cpp)
add_executable(cpp23_stacktrace_example ${CMAKE_SOURCE_DIR}/src/cpp23/cpp23_stacktrace_example.cpp)
add_executable(cpp23_expected_example ${CMAKE_SOURCE_DIR}/src/cpp23/cpp23_expected_example.cpp)
#add_executable(cpp23_mdspan_example ${CMAKE_SOURCE_DIR}/src/cpp23/cpp23_mdspan_example.cpp)
add_executable(cpp23_spanstream_example ${CMAKE_SOURCE_DIR}/src/cpp23/cpp23_spanstream_example.cpp)
add_executable(cpp23_split ${CMAKE_SOURCE_DIR}/src/cpp23/cpp23_split.cpp)
add_executable(cpp23_split2 ${CMAKE_SOURCE_DIR}/src/cpp23/cpp23_split2.cpp)
add_executable(cpp23_chunk ${CMAKE_SOURCE_DIR}/src/cpp23/cpp23_chunk.cpp)
#add_executable(cpp23_chunk2 ${CMAKE_SOURCE_DIR}/src/cpp23/cpp23_chunk2.cpp)
#add_executable(cpp23_chunk_by ${CMAKE_SOURCE_DIR}/src/cpp23/cpp23_chunk_by.cpp)
#add_executable(cpp23_chunk_by2 ${CMAKE_SOURCE_DIR}/src/cpp23/cpp23_chunk_by2.cpp)
add_executable(cpp23_remove_prefix ${CMAKE_SOURCE_DIR}/src/cpp23/cpp23_remove_prefix.cpp)
add_executable(cpp23_multi_dimensional_subscript_operator ${CMAKE_SOURCE_DIR}/src/cpp23/cpp23_multi_dimensional_subscript_operator.cpp)
add_executable(cpp23_assume ${CMAKE_SOURCE_DIR}/src/cpp23/cpp23_assume.cpp)
add_executable(cpp23_corouting_opt ${CMAKE_SOURCE_DIR}/src/cpp23/cpp23_corouting_opt.cpp)
