cmake_minimum_required(VERSION 3.28)
project(cpp23_learn)

set(CMAKE_CXX_STANDARD 23)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
add_executable(cpp23_barrier_main ${CMAKE_SOURCE_DIR}/src/cpp23/cpp23_barrier_main.cpp)
add_executable(cpp23_stdfloat_example ${CMAKE_SOURCE_DIR}/src/cpp23/cpp23_stdfloat_example.cpp)
add_executable(cpp23_stacktrace_example ${CMAKE_SOURCE_DIR}/src/cpp23/cpp23_stacktrace_example.cpp)
add_executable(cpp23_expected_example ${CMAKE_SOURCE_DIR}/src/cpp23/cpp23_expected_example.cpp)
#add_executable(cpp23_mdspan_example ${CMAKE_SOURCE_DIR}/src/cpp23/cpp23_mdspan_example.cpp)
add_executable(cpp23_spanstream_example ${CMAKE_SOURCE_DIR}/src/cpp23/cpp23_spanstream_example.cpp)
