cmake_minimum_required(VERSION 3.12)
project(cpp_learn)

set(CMAKE_CXX_STANDARD 11)

add_executable(myset_b_tree ../../src/myset_b_tree.cpp)
add_executable(virtual_main ../../src/virtual_main.cpp)
add_executable(simple_alloc_main ../../src/simple_alloc_main.cpp)
add_executable(singleton ../../src/singleton.cpp)
add_executable(isequal_main ../../src/isequal_main.cpp)
add_executable(cpp_err_handler ../../src/cpp_err_handler.cpp)
add_executable(getline ../../src/cpp11/getline.cpp)
#add_executable(testMyClass src/cpp11/main.cpp)
add_executable(testMyClass ../../src/cpp11/main.cpp ../../src/cpp11/MyClass.tpp)
add_executable(testMyClass2 ../../src/cpp11/main2.cpp)
add_executable(static_local ../../src/cpp11/static_local.cpp)
add_executable(t_local ../../src/cpp11/t_local.cpp)
add_executable(cpp11_test_suf ../../src/cpp11/test_suf.cpp)
add_executable(test_friend ../../src/cpp11/test_friend.cpp)
add_executable(cpp11_smatch ../../src/cpp11/cpp11_smatch.cpp)
add_executable(cpp11_condition_variable_main ${CMAKE_SOURCE_DIR}/src/cpp11/cpp11_condition_variable_main.cpp)
add_executable(cpp11_condition_variable_any_main ${CMAKE_SOURCE_DIR}/src/cpp11/cpp11_condition_variable_any_main.cpp)
add_executable(cpp11_cv_status_main ${CMAKE_SOURCE_DIR}/src/cpp11/cpp11_cv_status_main.cpp)
add_executable(cpp11_promise_main ${CMAKE_SOURCE_DIR}/src/cpp11/cpp11_promise_main.cpp)
add_executable(cpp11_shared_future_main ${CMAKE_SOURCE_DIR}/src/cpp11/cpp11_shared_future_main.cpp)
add_executable(cpp11_launch_main ${CMAKE_SOURCE_DIR}/src/cpp11/cpp11_launch_main.cpp)
add_executable(cpp11_future_status_main ${CMAKE_SOURCE_DIR}/src/cpp11/cpp11_future_status_main.cpp)
add_executable(cpp11_future_erro_main ${CMAKE_SOURCE_DIR}/src/cpp11/cpp11_future_erro_main.cpp)