cmake_minimum_required(VERSION 3.12)
project(cpp_learn)

set(CMAKE_CXX_STANDARD 11)

add_executable(cpp11_myset_b_tree ${CMAKE_SOURCE_DIR}/src/myset_b_tree.cpp)
add_executable(cpp11_virtual_main ${CMAKE_SOURCE_DIR}/src/virtual_main.cpp)
add_executable(cpp11_simple_alloc_main ${CMAKE_SOURCE_DIR}/src/simple_alloc_main.cpp)
add_executable(cpp11_singleton ${CMAKE_SOURCE_DIR}/src/singleton.cpp)
add_executable(cpp11_isequal_main ${CMAKE_SOURCE_DIR}/src/isequal_main.cpp)
add_executable(cpp11_cpp_err_handler ${CMAKE_SOURCE_DIR}/src/cpp_err_handler.cpp)
add_executable(cpp11_getline ${CMAKE_SOURCE_DIR}/src/cpp11/getline.cpp)
#add_executable(cpp11_testMyClass ${CMAKE_SOURCE_DIR}/src/cpp11/main.cpp)
add_executable(cpp11_testMyClass ${CMAKE_SOURCE_DIR}/src/cpp11/main.cpp ${CMAKE_SOURCE_DIR}/src/cpp11/MyClass.tpp)
add_executable(cpp11_testMyClass2 ${CMAKE_SOURCE_DIR}/src/cpp11/main2.cpp)
add_executable(cpp11_static_local ${CMAKE_SOURCE_DIR}/src/cpp11/static_local.cpp)
add_executable(cpp11_t_local ${CMAKE_SOURCE_DIR}/src/cpp11/t_local.cpp)
add_executable(cpp11_test_suf ${CMAKE_SOURCE_DIR}/src/cpp11/test_suf.cpp)
add_executable(cpp11_test_friend ${CMAKE_SOURCE_DIR}/src/cpp11/test_friend.cpp)
add_executable(cpp11_smatch ${CMAKE_SOURCE_DIR}/src/cpp11/cpp11_smatch.cpp)
#add_executable(cpp11_my ${CMAKE_SOURCE_DIR}/src/my.cpp)
add_executable(cpp11_constexpr_if ${CMAKE_SOURCE_DIR}/src/constexpr_if.cpp)