cmake_minimum_required(VERSION 3.12)
project(cpp_learn)

set(CMAKE_CXX_STANDARD 14)

add_executable(cpp14_sfinae_main ${CMAKE_SOURCE_DIR}/src/cpp14/cpp14_sfinae_main.cpp)
add_executable(cpp14_std_less ${CMAKE_SOURCE_DIR}/src/cpp14/cpp14_std_less.cpp)
add_executable(cpp14_greater_less_example ${CMAKE_SOURCE_DIR}/src/cpp14/cpp14_greater_less_example.cpp)
add_executable(cpp14_example_6-3-1 ${CMAKE_SOURCE_DIR}/src/cpp14/example/6-3-1.cpp)
add_executable(cpp14_example_6-3-1_success ${CMAKE_SOURCE_DIR}/src/cpp14/example/6-3-1_success.cpp)
target_link_libraries(cpp14_example_6-3-1_success pthread)
target_link_libraries(cpp14_example_6-3-1 pthread)
add_executable(cpp14_ownership_advance_ownership ${CMAKE_SOURCE_DIR}/src/cpp14/ownership/advance_ownership.cpp)
add_executable(cpp14_ownership_observer ${CMAKE_SOURCE_DIR}/src/cpp14/ownership/observer.cpp)
add_executable(cpp14_ownership_ownership ${CMAKE_SOURCE_DIR}/src/cpp14/ownership/ownership.cpp)
add_executable(cpp14_ownership_pass_ownership ${CMAKE_SOURCE_DIR}/src/cpp14/ownership/pass_ownership.cpp)
add_executable(cpp14_ownership_share_ownership ${CMAKE_SOURCE_DIR}/src/cpp14/ownership/share_ownership.cpp)
add_executable(cpp14_ownership_temporary_borrowing ${CMAKE_SOURCE_DIR}/src/cpp14/ownership/temporary_borrowing.cpp)
